
= eco 2020-08-08
:toc:

---

== From unthinkable to universal 普遍的；全体的；全世界的；共同的

(eco 2020-8-8 / United States / Taxing and spending: From unthinkable to universal)

Universal basic income *gains(v.) momentum* 推进力；动力；势头 in America

Paying for it *remains* another matter

Aug 8th 2020 | NEW YORK

- 从不可思议, 到普遍化 +
美国全民基本收入, 增长势头强劲 +
支付费用则是另一回事

COLETTE SMITH and her husband *are* both out of work. They *had exhausted their savings*, when she *received* a one-time $1,000 cash infusion 注入；灌输 *as part of a scheme* run(v.) by Neighbourhood Trust, a financial coaching  （体育运动、工作或技能的）训练，培训，指导 non-profit 不以营利为目的的；非营利的, and Humanity Forward, an organisation *devoted to building support for* universal basic income (UBI) 全民基本收入 *founded 把…基于；把…建立在 by* Andrew Yang. UBI *was* the centrepiece 最重要的项目（或物品）;桌子中央的装饰品 of Mr Yang’s run （尤指在美国）参加竞选 for the Democratic presidential nomination 提名, in which he *advocated* 拥护；支持；提倡 a guaranteed income of $1,000 a month, a “Freedom Dividend 红利；股息；股利”, *as he called it*, for every American adult, *regardless of* their financial circumstances.

- run : v. *~ (for sb/sth) | ~ (in sth)* to be a candidate in an election for a political position, especially in the US （尤指在美国）参加竞选
.. *to run for president* 竞选总统
.. *to run in the election* 参加竞选

- 科莱特·史密斯和她的丈夫都失业了。当他们耗尽了所有积蓄时，她收到了1000美元的一次性现金注入，这是由非营利金融辅导机构"邻里信托"(Neighbourhood Trust)和Humanity Forward运营的一个项目的一部分。后者致力于支持全民基本收入(universal basic income, UBI). 美国华裔民主党候选人杨安泽(Andrew Yang)把UBI作为政治纲领。UBI是杨在竞选民主党总统候选人提名时的核心政策主张，他在竞选中主张，无论经济状况如何，每个美国成年人都有每月1000美元的有保障收入，这是他所谓的“自由红利”。


There are two big hurdles 难关；障碍;（供人或马在赛跑中跨越的）栏架，跨栏 *to introducing* UBI *in* America. One *is building(v.) support(n.) for* something (that sounds, to many, alarmingly 惊人地；让人担忧地 socialist 社会主义者). The other *is working out* 找到…的答案；解决 how to pay for it. Mr Yang’s campaign (有计划的) 活动; 运动 for the Democratic nomination *may have failed*. But [on one of these points] he *has been wildly successful*. A recent Stanford study *showed that* people *are warming(v.) to* 对…更加感兴趣（或热衷） the UBI idea. In April 88% of liberals *backed it*, while support among conservatives  (观点) 保守的;右倾人士 *rose from 28%* before covid-19 *to 45%*. Universal benefits *can be easier* for politicians to sell, because they *are less vulnerable （身体上或感情上）脆弱的，易受…伤害的 to* the racial politics(n.) that *have undermined(v.) support for* welfare spending(n.) in the past.

- *work sth out*
1. to calculate sth 计算；算出
.. *to work out the answer* 计算出答案
2. to find the answer to sth 找到…的答案；解决
SYN solve
.. *to work out a problem* 解决问题
3. to plan or think of sth 计划；思考
.. *I've worked out a new way of doing it*. 我想出了做这事的一个新方法。

- *warm(v.) to/towards sb* : to begin to like sb 开始喜欢上（某人）
.. *I warmed to her* immediately. 我立即喜欢上了她。

- *warm(v.) to/towards sth* : to become more interested in or enthusiastic about sth 对…更加感兴趣（或热衷）
.. The speaker *was now warming to her theme*. 演讲者就她的主题越讲越起劲。

- 在美国推广UBI有两大障碍。其一是为一些在许多人看来令人担忧的社会主义观点建立支持。另一个问题是如何支付。杨的民主党提名竞选可能已经失败。但在其中一点上，他取得了巨大成功。斯坦福大学(Stanford)最近的一项研究表明，人们对UBI的想法越来越感兴趣。今年4月，88%的自由派支持该计划，而保守派的支持率从covid-19之前的28%, 上升到45%。对于政客们来说，全民福利更容易被接受，因为他们不太容易受到种族政治的影响。过去，种族政治削弱了人们对福利支出的支持。



Dreams of a UBI have a peculiar history in America. In 1967 a coalition of welfare recipients, led by African-American women, demanded “decent income as a right”. Martin Luther King wrote about it in his final book. At the other end of the political spectrum, Donald Rumsfeld and Dick Cheney drew up a guaranteed minimum-income proposal for President Richard Nixon. Milton Friedman and Friedrich Hayek, beloved of libertarians, were enthusiasts too.

More recently, UBI has been taken up by technologists who believe that software will leave a large number of Americans jobless, leading to social unrest. It has also been promoted by some of the organisations which make up the Black Lives Matter movement, who see it as a way to mend racial disparities in wealth.

Mr Yang points out that the approval rating for UBI was only about 25% when he began his presidential run, but by the time he ended it, in February, it was 66%. “The energy around universal basic income has skyrocketed, and it’s going to remain elevated until a bill passes,” says Mr Yang, who believes the job losses caused by covid-19 will not quickly be reversed. In June Jack Dorsey, Twitter’s boss, gave Mr Yang’s organisation $5m to build the case for UBI.

Funding a generous UBI has always seemed impossible. But many seemingly impossible economic policies have been enacted recently, opening the door to wackier ideas. Under America’s economic-stimulus plan to deal with the fallout from the pandemic, for example, Congress sent $1,200 to every adult. The scheme was so generous that, combined with extended unemployment benefits, aggregate household income is forecast to rise this year.

In May more than dozen cities, including Atlanta, Los Angeles, Newark and St Paul, along with the Economic Security Project, launched Mayors for a Guaranteed Income, a network of mayors experimenting with UBI-like schemes. Mr Dorsey has also given money to this group. In February 2019 Stockton, California, began an 18-month experiment to give $500 to 125 randomly selected people. This is being extended for another six months to help participants weather the slump.

In Jackson, Mississippi, the Magnolia Mothers’ Trust provides poor African-American mothers with $1,000 in cash monthly, no strings attached, for a year. It recently began a larger experiment with 75 more participants. Hudson, a small city in upstate New York, recently announced a five-year scheme to give a monthly $500 payment to 20 people. In Newark, New Jersey, Ras Baraka, the mayor, is hoping to get a pilot programme up and running. A third of Newark’s residents live in poverty and have to make tough decisions, Mr Baraka says, like “heat or eat.” Nearly 60% of Newark households carry delinquent debt. But to introduce a proper UBI in Newark, he says, would require federal funding.

For all the enthusiasm about UBI experiments, they remain problematic. It is hard to fully evaluate their effect because they are not universal (in the sense of received by everyone). Most take the form of occasional cash payments to poorer Americans. Nor are they generous enough to live on, which is what true UBI believers advocate. Finally, because they tend to be funded by philanthropy, the experiments do not factor in the substantial tax rises that would be needed to pay for them.

The proposal Mr Yang ran on would have cost $2.8trn annually, which is about what the federal government spends each year on Social Security (pensions), Medicare (health care for the elderly) and Medicaid (health care for the poor) combined. Even then it would provide adults with no more than $12,000 a year—not enough to lift a workless family with two adults and two children above the federal poverty line.

A more targeted effort that did not aim to be universal could do much more on that score. Ms Smith, along with 1,000 other residents of the Bronx, received a one-off $1,000 grant from Mr Yang’s outfit. This allowed her to buy food and to restore the internet, which her 14-year-old son needed for remote learning. This helped a great deal. But UBI advocates still have to explain why it would not be better to give families such as hers larger sums rather than a smaller payment that also goes to those who do not need it.


---

== From unthinkable to universal

Universal basic income gains momentum in America

Paying for it remains another matter

Aug 8th 2020 | NEW YORK


COLETTE SMITH and her husband are both out of work. They had exhausted their savings, when she received a one-time $1,000 cash infusion as part of a scheme run by Neighbourhood Trust, a financial coaching non-profit, and Humanity Forward, an organisation devoted to building support for universal basic income (UBI) founded by Andrew Yang. UBI was the centrepiece of Mr Yang’s run for the Democratic presidential nomination, in which he advocated a guaranteed income of $1,000 a month, a “Freedom Dividend”, as he called it, for every American adult, regardless of their financial circumstances.

There are two big hurdles to introducing UBI in America. One is building support for something that sounds, to many, alarmingly socialist. The other is working out how to pay for it. Mr Yang’s campaign for the Democratic nomination may have failed. But on one of these points he has been wildly successful. A recent Stanford study showed that people are warming to the UBI idea. In April 88% of liberals backed it, while support among conservatives rose from 28% before covid-19 to 45%. Universal benefits can be easier for politicians to sell, because they are less vulnerable to the racial politics that have undermined support for welfare spending in the past.

Dreams of a UBI have a peculiar history in America. In 1967 a coalition of welfare recipients, led by African-American women, demanded “decent income as a right”. Martin Luther King wrote about it in his final book. At the other end of the political spectrum, Donald Rumsfeld and Dick Cheney drew up a guaranteed minimum-income proposal for President Richard Nixon. Milton Friedman and Friedrich Hayek, beloved of libertarians, were enthusiasts too.

More recently, UBI has been taken up by technologists who believe that software will leave a large number of Americans jobless, leading to social unrest. It has also been promoted by some of the organisations which make up the Black Lives Matter movement, who see it as a way to mend racial disparities in wealth.

Mr Yang points out that the approval rating for UBI was only about 25% when he began his presidential run, but by the time he ended it, in February, it was 66%. “The energy around universal basic income has skyrocketed, and it’s going to remain elevated until a bill passes,” says Mr Yang, who believes the job losses caused by covid-19 will not quickly be reversed. In June Jack Dorsey, Twitter’s boss, gave Mr Yang’s organisation $5m to build the case for UBI.

Funding a generous UBI has always seemed impossible. But many seemingly impossible economic policies have been enacted recently, opening the door to wackier ideas. Under America’s economic-stimulus plan to deal with the fallout from the pandemic, for example, Congress sent $1,200 to every adult. The scheme was so generous that, combined with extended unemployment benefits, aggregate household income is forecast to rise this year.

In May more than dozen cities, including Atlanta, Los Angeles, Newark and St Paul, along with the Economic Security Project, launched Mayors for a Guaranteed Income, a network of mayors experimenting with UBI-like schemes. Mr Dorsey has also given money to this group. In February 2019 Stockton, California, began an 18-month experiment to give $500 to 125 randomly selected people. This is being extended for another six months to help participants weather the slump.

In Jackson, Mississippi, the Magnolia Mothers’ Trust provides poor African-American mothers with $1,000 in cash monthly, no strings attached, for a year. It recently began a larger experiment with 75 more participants. Hudson, a small city in upstate New York, recently announced a five-year scheme to give a monthly $500 payment to 20 people. In Newark, New Jersey, Ras Baraka, the mayor, is hoping to get a pilot programme up and running. A third of Newark’s residents live in poverty and have to make tough decisions, Mr Baraka says, like “heat or eat.” Nearly 60% of Newark households carry delinquent debt. But to introduce a proper UBI in Newark, he says, would require federal funding.

For all the enthusiasm about UBI experiments, they remain problematic. It is hard to fully evaluate their effect because they are not universal (in the sense of received by everyone). Most take the form of occasional cash payments to poorer Americans. Nor are they generous enough to live on, which is what true UBI believers advocate. Finally, because they tend to be funded by philanthropy, the experiments do not factor in the substantial tax rises that would be needed to pay for them.

The proposal Mr Yang ran on would have cost $2.8trn annually, which is about what the federal government spends each year on Social Security (pensions), Medicare (health care for the elderly) and Medicaid (health care for the poor) combined. Even then it would provide adults with no more than $12,000 a year—not enough to lift a workless family with two adults and two children above the federal poverty line.

A more targeted effort that did not aim to be universal could do much more on that score. Ms Smith, along with 1,000 other residents of the Bronx, received a one-off $1,000 grant from Mr Yang’s outfit. This allowed her to buy food and to restore the internet, which her 14-year-old son needed for remote learning. This helped a great deal. But UBI advocates still have to explain why it would not be better to give families such as hers larger sums rather than a smaller payment that also goes to those who do not need it.

---



UBI梦在美国有一段特殊的历史。1967年，一个由非裔美国妇女领导的福利接受者联盟要求“体面的收入作为一项权利”。马丁·路德·金在他的最后一本书中写道。在政治谱系的另一端，唐纳德·拉姆斯菲尔德和迪克·切尼为理查德·尼克松总统起草了一份保证最低收入的提案。深受自由意志主义者喜爱的米尔顿•弗里德曼(Milton Friedman)和弗里德里希•哈耶克(Friedrich Hayek)也是狂热分子。
最近，UBI已经被一些技术专家所接受，他们认为软件将导致大量美国人失业，导致社会动荡。“黑人的命也是命”运动的一些组织也在推广这项运动，他们认为这是一种弥补贫富差距的方法。
杨指出，当他开始总统竞选时，UBI的支持率只有25%左右，但当他在2月份结束竞选时，支持率已经达到66%。杨表示:“围绕全民基本收入的热情已经飙升，在法案通过之前，这种热情还将持续高涨。”他认为，新冠肺炎造成的失业不会很快得到扭转。6月，推特的老板杰克·多尔西给了杨先生的组织500万美元来为UBI打官司。

资助一个慷慨的UBI似乎总是不可能的。但最近出台了许多看似不可能的经济政策，为更古怪的想法打开了大门。例如，在美国经济刺激计划中，为了应对疫情的影响，国会给每个成年人发放了1200美元。该计划如此慷慨，再加上失业救济金的延长，预计今年的家庭总收入将会上升。
今年5月，包括亚特兰大、洛杉矶、纽瓦克和圣保罗在内的十多个城市，与经济安全项目一起启动了“有保障收入的市长”(Mayors for a Guaranteed Income)项目，这是一个由市长组成的网络，他们正在试验类似ubiity的方案。多尔西也向该集团提供了资金。2019年2月，加利福尼亚州的斯托克顿市开始了一项为期18个月的实验，向随机挑选的125人赠送500美元。这项计划将再延长6个月，以帮助参与者度过经济低迷期。
在密西西比州的杰克逊市，木兰花母亲信托基金(Magnolia Mothers’s Trust)每年都会向贫穷的非洲裔美国母亲每月提供1000美元现金，没有任何附加条件。它最近开始了一项更大的实验，有75名参与者。纽约北部的小城哈德逊最近宣布了一项为期五年的计划，每月为20个人提供500美元的补助。在新泽西州的纽瓦克市，市长拉斯•巴拉卡(Ras Baraka)希望启动并实施一个试点项目。巴拉卡说，纽瓦克三分之一的居民生活贫困，不得不做出艰难的决定，比如“加热还是吃”。纽瓦克有近60%的家庭拖欠债务。但是他说，在纽瓦克引进一个合适的UBI需要联邦资金。
尽管人们对UBI实验充满热情，但它们仍然存在问题。很难全面评估它们的效果，因为它们并不是普遍的(在每个人都接受的意义上)。大多数都采取偶尔向较贫穷的美国人支付现金的形式。他们也不够慷慨地生活，这是真正的UBI信徒所提倡的。最后，由于这些实验的资金来源往往是慈善事业，因此这些实验并没有考虑到为它们提供资金所需的大幅增税。
杨先生提出的提案每年将花费2.8万亿美元，相当于联邦政府每年在社会保障(养老金)、医疗保险(老年人的医疗保健)和医疗补助(穷人的医疗保健)上的支出之和。即便如此，它也只能为成年人提供不超过1.2万美元的年收入——不足以让一个有两个成年人和两个孩子的无工作家庭摆脱联邦贫困线。
在这方面，不以普遍性为目标的更具针对性的努力可以发挥更大的作用。史密斯女士和布朗克斯区其他1000名居民从杨先生的机构获得了一次性的1000美元补助。这使她能够购买食物，并恢复了她14岁的儿子进行远程学习所需的互联网。这帮了大忙。但UBI的支持者仍然需要解释，为什么给像她这样的家庭更多的补贴，不如给那些不需要的家庭更少的补贴。